modLoader="javafml"
loaderVersion="[28,)"
# issueTrackerURL=""

[[mods]]
modId="neoarsenal"
version="1.1.1"
mcversion= "1.14,"
displayName="NeoArsenal"
# displayURL=""
authors="Zorochase"
description='''
A new arsenal for modern Minecraft.
'''

[[dependencies.neoarsenal]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.0,)"
    ordering="NONE"
    side="BOTH"