modLoader="javafml"
loaderVersion="[28,)"
# issueTrackerURL=""

[[mods]]
modId="neoarsenal"
version="1.0.0"
mcversion= "1.14,"
displayName="NeoArsenal"
# displayURL=""
authors="Zorochase"
description='''
A mod adding trait-swapping tools, FE-based machines and other utilities.
'''

[[dependencies.neoarsenal]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.0,)"
    ordering="NONE"
    side="BOTH"